#!/bin/sh

psfsetpsnames -i source/glyph_data.csv source/Andika-Regular.ufo
psfsetpsnames -i source/glyph_data.csv source/Andika-Italic.ufo
psfsetpsnames -i source/glyph_data.csv source/Andika-Bold.ufo
psfsetpsnames -i source/glyph_data.csv source/Andika-BoldItalic.ufo
psfsetglyphorder --header sort_final_a -i source/glyph_data.csv source/Andika-Regular.ufo
psfsetglyphorder --header sort_final_a -i source/glyph_data.csv source/Andika-Italic.ufo
psfsetglyphorder --header sort_final_a -i source/glyph_data.csv source/Andika-Bold.ufo
psfsetglyphorder --header sort_final_a -i source/glyph_data.csv source/Andika-BoldItalic.ufo
psfsyncmeta source/Andika-Regular.ufo
