#!/bin/sh

echo "-----Fixing FontForge debris and normalizing UFOs..."
psffixffglifs source/masters/Andika-Regular.ufo -p checkfix=fix     &
psffixffglifs source/masters/Andika-Bold.ufo -p checkfix=fix        &
psffixffglifs source/masters/Andika-Italic.ufo -p checkfix=fix      &
psffixffglifs source/masters/Andika-BoldItalic.ufo -p checkfix=fix  &
wait

echo "-----Updating production names in Regular..."
psfsetpsnames -q -p checkfix=fix -i source/glyph_data.csv source/masters/Andika-Regular.ufo -p backup=False -x

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final_a -i source/glyph_data.csv source/masters/Andika-Regular.ufo -p backup=False -x

echo "-----Rebuilding composites..."
psfbuildcomp -i source/composites.txt -c -n source/masters/Andika-Regular.ufo -p backup=False
psfbuildcomp -i source/composites.txt -c -n source/masters/Andika-Bold.ufo -p backup=False
psfbuildcomp -i source/composites.txt -c -n source/masters/Andika-Italic.ufo -p backup=False
psfbuildcomp -i source/composites.txt -c -n source/masters/Andika-BoldItalic.ufo -p backup=False

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters --complex -q source/AndikaRoman.designspace source/AndikaItalic.designspace

# echo "-----Updating woff metadata file..."
# psfmakewoffmetadata -q -n "Andika" -i "org.sil.fonts" source/masters/Andika-Regular.ufo

echo "-----Preflight completed!"
