#!/bin/sh

echo "-----Updating UFOs from Glyphs file..."
psfglyphs2ufo --nofea source/AndikaRoman.glyphs source  &
psfglyphs2ufo --nofea source/AndikaItalic.glyphs source &
wait

echo "-----Normalizing Regular UFO..."
echo "-----Updating production names in Regular..."
psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/Andika-Regular.ufo -x

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final_a -i source/glyph_data.csv source/Andika-Regular.ufo -p backup=False -x

echo "-----Normalizing other UFOs..."
psfnormalize -p checkfix=fix source/Andika-Bold.ufo       &
psfnormalize -p checkfix=fix source/Andika-Italic.ufo     &
psfnormalize -p checkfix=fix source/Andika-BoldItalic.ufo &
wait

# add building of composites here

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/AndikaRoman.designspace source/AndikaItalic.designspace

 # Fix problem with non-spacing marks due to glyphsLib bug
echo "-----Fixing width of non-spacing marks..."
psfremovegliflibkeys -q source/Andika-Regular.ufo com.schriftgestaltung.Glyphs.originalWidth    &
psfremovegliflibkeys -q source/Andika-Bold.ufo com.schriftgestaltung.Glyphs.originalWidth       &
psfremovegliflibkeys -q source/Andika-Italic.ufo com.schriftgestaltung.Glyphs.originalWidth     &
psfremovegliflibkeys -q source/Andika-BoldItalic.ufo com.schriftgestaltung.Glyphs.originalWidth &
wait

echo "-----Preflight completed!"
